"""survey structuration models

Revision ID: 311309a4cc6b
Revises: 4ba6d9e427c8
Create Date: 2025-10-17 13:26:05.436184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311309a4cc6b'
down_revision: Union[str, Sequence[str], None] = '4ba6d9e427c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    fs_question_types = op.create_table('fs_question_types',
    sa.Column('id_question_type', sa.Integer(), nullable=False),
    sa.Column('question_type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_question_type')
    )
    op.create_table('fs_questions',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('question_name', sa.String(), nullable=False),
    sa.Column('id_question_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_question_type'], ['fs_question_types.id_question_type'], name='fk_question_type'),
    sa.PrimaryKeyConstraint('id_question')
    )
    op.create_table('fs_sections',
    sa.Column('id_section', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('id_survey', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_survey'], ['fs_surveys.id_survey'], name='fk_section', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_section')
    )
    op.create_table('fs_options',
    sa.Column('id_option', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_question'], ['fs_questions.id_question'], name='fk_question'),
    sa.PrimaryKeyConstraint('id_option')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        fs_question_types,
        [
            {"question_type_name": "Header"},
            {"question_type_name": "Text"},
            {"question_type_name": "TextArea"},
            {"question_type_name": "DateTime"},
            {"question_type_name": "ComboBox"},
            {"question_type_name": "RadioButton"},
            {"question_type_name": "CheckList"},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fs_options')
    op.drop_table('fs_sections')
    op.drop_table('fs_questions')
    op.drop_table('fs_question_types')
    # ### end Alembic commands ###
