"""add unique to survey name

Revision ID: 4ba6d9e427c8
Revises: aabdb01b1217
Create Date: 2025-10-14 21:16:55.924625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba6d9e427c8'
down_revision: Union[str, Sequence[str], None] = 'aabdb01b1217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fs_surveys', ['survey_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fs_surveys', type_='unique')
    # ### end Alembic commands ###
