"""added ondelete on questions and options

Revision ID: 55483b0eb2cc
Revises: b110f064bb38
Create Date: 2025-10-27 17:15:18.520877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55483b0eb2cc'
down_revision: Union[str, Sequence[str], None] = 'b110f064bb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_question'), 'fs_options', type_='foreignkey')
    op.create_foreign_key('fk_question', 'fs_options', 'fs_questions', ['id_question'], ['id_question'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_section'), 'fs_questions', type_='foreignkey')
    op.create_foreign_key('fk_section', 'fs_questions', 'fs_sections', ['id_section'], ['id_section'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_section', 'fs_questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_section'), 'fs_questions', 'fs_sections', ['id_section'], ['id_section'])
    op.drop_constraint('fk_question', 'fs_options', type_='foreignkey')
    op.create_foreign_key(op.f('fk_question'), 'fs_options', 'fs_questions', ['id_question'], ['id_question'])
    # ### end Alembic commands ###
