"""added id_section in questions

Revision ID: b110f064bb38
Revises: 311309a4cc6b
Create Date: 2025-10-17 13:57:02.864583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b110f064bb38'
down_revision: Union[str, Sequence[str], None] = '311309a4cc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fs_questions', sa.Column('id_section', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_section', 'fs_questions', 'fs_sections', ['id_section'], ['id_section'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_section', 'fs_questions', type_='foreignkey')
    op.drop_column('fs_questions', 'id_section')
    # ### end Alembic commands ###
