"""baseline

Revision ID: dfbaa5314224
Revises: 
Create Date: 2025-09-30 20:44:29.307430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbaa5314224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_permissions',
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_permission')
    )
    op.create_table('fs_roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('role_state', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('fs_roles_permissions',
    sa.Column('id_roles_permissions', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_permission', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_permission'], ['fs_permissions.id_permission'], name='fk_permission', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_role'], ['fs_roles.id_role'], name='fk_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_roles_permissions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fs_roles_permissions')
    op.drop_table('fs_roles')
    op.drop_table('fs_permissions')
    # ### end Alembic commands ###
