from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dfbaa5314224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fs_permissions',
        sa.Column('id_permission', sa.Integer(), primary_key=True),
        sa.Column('permission_name', sa.String(), nullable=False)
    )
    op.create_table(
        'fs_roles',
        sa.Column('id_role', sa.Integer(), primary_key=True),
        sa.Column('role_name', sa.String(length=50), nullable=False),
        sa.Column('creation_date', sa.Date(), nullable=False),
        sa.Column('role_state', sa.Integer(), nullable=False),
        sa.Column('update_date', sa.Date(), nullable=True)
    )
    op.create_table(
        'fs_roles_permissions',
        sa.Column('id_roles_permissions', sa.Integer(), primary_key=True),
        sa.Column('id_role', sa.Integer(), sa.ForeignKey('fs_roles.id_role', name='fk_role', ondelete='CASCADE')),
        sa.Column('id_permission', sa.Integer(), sa.ForeignKey('fs_permissions.id_permission', name='fk_permission', ondelete='CASCADE'))
    )

    permissions_table = sa.table(
        "fs_permissions",
        sa.column("permission_name", sa.String)
    )

    op.bulk_insert(
        permissions_table,
        [
            {"permission_name": "Inicio"},
            {"permission_name": "Creación de Encuestas"},
            {"permission_name": "Administrar Encuestas"},
            {"permission_name": "Administrar Usuarios"},
            {"permission_name": "Administrar Roles"},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fs_roles_permissions')
    op.drop_table('fs_roles')
    op.drop_table('fs_permissions')
    # ### end Alembic commands ###